### ISSUE TITLE
ServerError: post type from endpoints "posts,pages,media" with slug "hello-frontity" not found

### ISSUE THREAD

**Issue by juanmaguitar** [frontity/step-by-step-tutorial#5]
In the Step "Creating a Custom Theme > Connect the <Root> component to the state"
When accessing http://localhost:3000/hello-frontity
The terminal returns an error

```
ServerError: post type from endpoints "posts,pages,media" with slug "hello-frontity" not found
    at Object.eval (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/handlers/postType.ts:37:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at eval (webpack-internal:///./node_modules/@frontity/wp-source/src/actions.ts:24:1) {
  status: 404,
  statusText: 'post type from endpoints "posts,pages,media" with slug "hello-frontity" not found'
}
```

 I suggest to change that URL example for "http://localhost:3000/about-us/" that is an URL that actually exists in https://test.frontity.org/about-us/

**Comment by mburridge** [comment]
Text changed and new screengrab image created to replace old one.
